### PR TITLE
Update browser detection to work with IE 11, handle initial hash, add options

### PR DESCRIPTION
**Pull request by backflip**
When discovering that the script did not work in IE 11, I had a look at https://github.com/Automattic/_s/blob/master/js/skip-link-focus-fix.js

Would you consider updating this fork to the changes there?

### CODE REVIEW

**Comment by bradyvercher** [comment]
Do you know if there was any discussion around that update?

Adding support for IE 11 would be good and I don't mind dropping support for Webkit and Opera, but I do remember Chrome not skipping to the content if the hash was already present in the address bar, so this might require a bit more testing around that.

**Comment by backflip** [comment]
Hey @bradyvercher, thanks for the quick answer! I'll briefly test this in a few browsers since I can't find anything in https://github.com/Automattic/_s/commit/9a988eae35bcb44981afe515da49b098b0b6b355.

While we're at it: Could it make sense to make the selector in https://github.com/cedaro/skip-link-focus/blob/develop/skip-link-focus.js#L31 configurable? And do you remember the specific use case there? Is this a fallback for browsers not firing the `hashchange` event in some situations?

**Comment by bradyvercher** [comment]
If you've got a need for making the selector configurable, I'm not opposed.

If I recall correctly, the `for` loop handled cases where the hash was present in the URL on initial load (or refresh), so clicking the skip link wouldn't actually fire a `hashchange` event, making the skip link unusable in that scenario.

**Comment by backflip** [comment]
Sounds reasonable.

I'm currently testing the behavior on initial hash and I guess we'll need something along the following lines for this to work:
```
if ( location.hash && location.hash.substring( 1 ) ) {
	skipToElement( location.hash.substring( 1 ) );
}
```

And you're absolutely right that Chrome does not handle this properly by default. It seems to work on initial page load but not on reload, so it would definitely make sense to re-enable this script for Chrome (and add above block).

What do you think?

**Comment by backflip** [comment]
I have updated the PR accordingly. 
Or would you rather hide this behavior behind an option (if at all)?

**Comment by bradyvercher** [comment]
Thanks @backflip! This is looking good. After a bit of testing, it looks like Firefox and Safari automatically skip on load and reload if a hash is present, so we can leave that enabled by default to mimic behavior in those browsers.

Instead of passing the selector as the first parameter, how about we make that an object so it can be extended in the future if necessary? Maybe something like this:

```js
function init( options ) {
...
options = options || {};
options.selector = options.selector || '.skip-link';
...
}
```
Then when calling init(), the selector can be passed in like this:
```js
skipLinkFocus.init({ selector: '.custom-skip-link-class' });
```

I think it's good to go after that.

**Comment by backflip** [comment]
@bradyvercher, sounds good to me. I have updated the PR.

**Comment by bradyvercher** [comment]
Thanks again for the update @backflip! I've merged these changes and released them in version 1.0.0.

**Pull request merged**
